import Head from 'next/head';
import { useEffect, useContext } from 'react';
import { authContext } from '../contexts/authWrapper';

export default function Home() {

  const { authUser, logout } = useContext(authContext);

  useEffect(() => {
    console.log('use effect of /');
    console.log('printing user from / =', authUser);
  }, []);

  //handle logout
  const handleLogout = async () => {
       if(authUser){
         await logout();
       }
  }

  console.log('render of / called');
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        Main page
        <button onClick={handleLogout}>Sign Out</button>
      </section>
    </div>
  )
}
